### ISSUE TITLE
2.0.0 release candidate checklist

### ISSUE THREAD

**Issue by danvk** [danvk/dygraphs#814]
- [ ] Write release notes
- [x] Push an RC to npm
- [x] Bump all versions to 2.0.0
- [x] Paths to CSS and JS are broken on website /tests/
- [x] Publish a [sample repo using webpack / rollup][1]
- [x] Update tutorial.
- [x] Add npm install & ES6 import instructions to the home page
- [x] Get node install working; follow d3's lead here.
- [x] Add a minified CSS file
- [x] Make passing strings in raw format an error.
- [x] Look into whether the symbol/iterator polyfill can be shrunk.
- [x] Update all references to `dygraph-combined.js` and `dygraph-combined-dev.js`.
- [x] Remove or deprecate `timingName` option.
- [x] Remove deprecated options (just `avoidMinZero`).

[1]: https://github.com/danvk/dygraphs-es6
